.TH asterion 0 2017-nov "linux" "heatherly custom tools manual"

.SH NAME
asterion_minotaur \- radial convergence diagram navigator

.SH IMAGERY (see HERITAGE at bottom for more)
head of a bull, body of a man, and master of the labyrinth in crete

.SH SUMMARY
.B asterion 
is a fast, sweet code/graph navigation tool that visually demonstrates connections
between functions using a radial convergence diagram.

.SH SCOPE, REASONING and DECISION

.B definition (D).  
radial convergence diagrams (RCD) allow the compact display of complex
interrelationships (edges) between large number of entities (nodes).

.B what the hell (?).  
i am tackling this problem because it has very high value for code analysis.
once i beat that, i will genericize to many uses.

.B complication (C).  
this is rare and complex ;) i could use super fat, nasty packages software,
but i would rather be wayed and measured against the titans.

.B answer (A).  
build a fast, sweet, opengl solution that uses standard vi_keys for navigation.

.B target user (T).  
as always, very technical, well-versed, power user.

.B drawbacks...
   -- steep learning curve between subject and code
   -- hard to make it asthetic and beautiful
   -- takes a lot of time to define to built it
   -- takes a lot of willpower to stay with it (no problem)
   -- will never release my application to others (do not care)

.B benefits...
   -- learn a shit-ton of graphics techniques
   -- once its built, i can expand and modify
   -- put more pressure on vi_keys to test its definition
   -- never need a mouse, only good use of joystick and touchpad

.SH SEE ALSO
this documentation is layered to provide easier navigation.
   asterion (1), command line usage and options
   asterion (6), interactive system usage and navigation
   asterion (7), decision rationale, objectives, and overview

.SH AUTHOR
jelloshrike at gmail dot com

.SH COLOPHON
this page is part of a documentation package meant to make use of the
heatherly tools easier and faster.
