#!/bin/bash

grep "^[a-z][A-Za-z]  [A-Za-z][A-Za-z]" HTAG.tags    > call_graph
printf "\n"                                         >> call_graph
cat  HTAG.flow                                      >> call_graph

echo "#!/usr/local/bin/gyges"
echo "#   generated by labyrinth (asterion) for use in gyges"
echo "#---------  ver  ---loc--  size "
echo "width       -A-  0a1         14 "

